# Generated by Django 3.2 on 2021-04-19 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_remove_student_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateTimeField(verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.CharField(max_length=200, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='student',
            name='home_town',
            field=models.CharField(max_length=200, verbose_name='Home town'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='registration_number',
            field=models.CharField(help_text='Please use the following format: <em>YYYY-MM-DD</em>.', max_length=11, primary_key=True, serialize=False, verbose_name='Registration Number'),
        ),
        migrations.AlterField(
            model_name='student',
            name='score',
            field=models.IntegerField(default=0, verbose_name='Score'),
        ),
    ]
