# Generated by Django 3.2 on 2021-04-24 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_student_register_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='student',
            name='registration_number',
            field=models.CharField(help_text='Please use the following format: SE-(<em>Number</em>).', max_length=11, primary_key=True, serialize=False, verbose_name='Registration Number'),
        ),
    ]
